NAME = libft.a
HEAD := -I .

CFLAGS = -Wall -Wextra -Werror

BNS := \
	ft_lstmap.c \
	ft_lstiter.c \
	ft_lstclear.c \
	ft_lstlast.c \
	ft_lstdelone.c \
	ft_lstsize.c \
	ft_lstadd_back.c \
	ft_lstadd_front.c \
	ft_lstnew.c \

SRC := \
	ft_memset.c \
	ft_check_argv.c \
	ft_bzero.c \
	ft_memcpy.c \
	ft_memccpy.c \
	ft_memmove.c \
	ft_atof.c \
	ft_atof_1.c \
	ft_memchr.c \
	ft_memcmp.c \
	ft_strlen.c \
	ft_get_next_line.c \
	ft_isalpha.c \
	ft_isdigit.c \
	ft_rmv_tab.c \
	ft_isalnum.c \
	ft_isascii.c \
	ft_isprint.c \
	ft_toupper.c \
	ft_tolower.c \
	ft_strchr.c \
	ft_strrchr.c \
	ft_strncmp.c \
	ft_strlcpy.c \
	ft_strlcat.c \
	ft_strnstr.c \
	ft_atoi.c \
	ft_atoi_count.c \
	ft_intlength.c \
	ft_doublength.c \
	ft_calloc.c \
	ft_strdup.c \
	ft_substr.c \
	ft_strjoin.c \
	ft_strtrim.c \
	ft_split.c \
	ft_itoa.c \
	ft_strmapi.c \
	ft_putchar_fd.c \
	ft_putstr_fd.c \
	ft_putendl_fd.c \
	ft_putnbr_fd.c \
	ft_free_split.c \

OBJS :=$(SRC:.c=.o)
OBJB :=$(BNS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

bonus: $(OBJS) $(OBJB)
	ar rcs $(NAME) $(OBJS) $(OBJB)

%.o: %.c
	gcc $(CFLAGS) $(HEAD) -c $< -o $@

clean:
	rm -rf $(OBJS) $(OBJB)

fclean:
	rm -rf $(NAME) $(OBJS) $(OBJB)

re: fclean all
